### ISSUE TITLE
Meteor 1.3 support?

### ISSUE THREAD

**Issue by Sabst** [nicolaslopezj/meteor-react-form#1]
Even if it's maybe early for that, it would be nice to support 1.3 (and Mantra?).
For example, the new testing capabilities could be used. 

I did some experiments with beta.6/Mantra and had these issues so far:
- incompatibility with wallaby.js file (just removed the file for now but a more detailed analysis is required)
- could not solve the _multiple react copies loaded_ puzzle  (see for example https://github.com/callemall/material-ui/issues/2818)... can we still use legacy packages pulling React or do we have to use npm instead?

It looks like these will have to be fixed before going further with 1.3... a specific branch will probably be required.

Thank you for this key package!

**Comment by nicolaslopezj** [comment]
Once 1.3 is released this will support it. 
I think that MRF should be a npm package, but first simple schema must be on npm. I hope aldeed release it when 1.3 launches.

**Comment by nicolaslopezj** [comment]
I'm working on 1.3 support on this branch https://github.com/nicolaslopezj/meteor-react-form/tree/1.3-with-node.

The only problem I'm having is with the dependency!

Meteor must fix this issue meteor/meteor#5890

**Comment by Sabst** [comment]
FYI, I stopped using the meteor packages pulling react (and material-ui).
I'm directly using the npm modules instead.
Obviously, no fix is required in that case. The downside is that the application defines the dependencies and not the MRF packages (but if they later become modules, that will be ok).

**Comment by d-winter** [comment]
I am getting this error when trying this package with Meteor 1.3 beta 12 and react and material from npm:

Uncaught ReferenceError: DotObject is not defined(anonymous function) 
@ form.jsx:179mapSingleChildIntoContext 
@ ReactChildren:105traverseAllChildrenImpl 
@ traverseAllChildren:98traverseAllChildrenImpl
@ traverseAllChildren:114traverseAllChildren 
@ traverseAllChildren:186mapIntoWithKeyPrefixInternal 
@ ReactChildren:125mapChildren 
@ ReactChildren:145renderChildren 
@ form.jsx:173render 
@ form.jsx:233ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext 
@ ReactComponentEnvironment.js:2ReactCompositeComponentMixin._renderValidatedComponent 
@ ReactComponentEnvironment.js:22wrapper 
@ setInnerHTML.js:79ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:339wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent 
@ ReactRef.js:39ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:344wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent 
@ ReactRef.js:39ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:344wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent
@ ReactRef.js:39ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:344wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39ReactMultiChild.Mixin.mountChildren 
@ ReactMultiChild.js:360ReactDOMComponent.Mixin._createContentMarkup 
@ ReactDOMComponent.js:710ReactDOMComponent.Mixin.mountComponent 
@ ReactDOMComponent.js:598ReactReconciler.mountComponent 
@ ReactRef.js:39ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:344wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39ReactCompositeComponentMixin.mountComponent 
@ ReactCompositeComponent.js:344wrapper 
@ setInnerHTML.js:79ReactReconciler.mountComponent 
@ ReactRef.js:39mountComponentIntoNode 
@ ReactMount.js:385Mixin.perform 
@ instantiateReactComponent.js:14batchedMountComponentIntoNode 
@ ReactMount.js:401ReactDefaultBatchingStrategy.batchedUpdates 
@ ReactDOMComponent.js:102batchedUpdates 
@ ReactUpdates.js:213ReactMount._renderNewRootComponent 
@ ReactMount.js:595wrapper 
@ setInnerHTML.js:79ReactMount._renderSubtreeIntoContainer 
@ ReactMount.js:669ReactMount.renderSubtreeIntoContainer 
@ ReactMount.js:620_renderLayer 
@ arrow-drop-down.js:5componentDidMount 
@ modules.js?hash=b3761c5114a448a53e96a7c6fbe9b3e63cfb8f8a:31689assign.notifyAll 
@ PooledClass.js:81ON_DOM_READY_QUEUEING.close 
@ ReactInputSelection.js:39Mixin.closeAll 
@ instantiateReactComponent.js:80Mixin.perform 
@ instantiateReactComponent.js:27Mixin.perform 
@ instantiateReactComponent.js:14assign.perform 
@ ReactUpdates.js:205flushBatchedUpdates 
@ CallbackQueue.js:33wrapper
@ setInnerHTML.js:79Mixin.closeAll 
@ instantiateReactComponent.js:80Mixin.perform 
@ instantiateReactComponent.js:27ReactDefaultBatchingStrategy.batchedUpdates 
@ ReactDOMComponent.js:104batchedUpdates 
@ ReactUpdates.js:213ReactEventListener.dispatchEvent 
@ ReactClass.js:54

Any ideas?

**Comment by Sabst** [comment]
In mrf/form.jsx, try to add:
`import DotObject from './dot.js';`

**Comment by d-winter** [comment]
@Sabst do I have to edit the file within ~/.meteor/packages/nicolaslopezj_mrf? When starting the app I get the following error:
While processing files with ecmascript (for target web.browser):
   packages/nicolaslopezj:mrf/form.jsx:242:29: Unexpected token (242:29)
Sorry, but I am not so familiar with meteors package/build system..
Thanks a lot for your help!

**Comment by Sabst** [comment]
I'm unsure about the error you get.
I need to update my environment with the latest MRF commits to be more precise.
I did not edit directly in `~/.meteor/...` but copied the `packages` directory from MRF in my application directory... this is where I edited the files like `packages/mrf/form.jsx`.

**Comment by nicolaslopezj** [comment]
I created a npm version of this package that works with Meteor 1.3

https://github.com/nicolaslopezj/simple-react-form

**Comment by SachaG** [comment]
Oh that's awesome! Great work :)

**Comment by nicolaslopezj** [comment]
Thanks!
