### ISSUE TITLE
Error: Invalid definition for body field

### ISSUE THREAD

**Issue by vonwao** [nicolaslopezj/meteor-react-form#12]
For some reason I get an error.  As soon as I add mrf attribute to SimpleSchema field, like:

```
    mrf: {
      type: 'textarea',
    }

```

Error: Invalid definition for body field.
at packages/aldeed_simple-schema/simple-schema.js:457:1

I installed:
nicolaslopezj:mrf
nicolaslopezj:mrf-material-ui

Any idea why I get this error?

**Comment by nicolaslopezj** [comment]
Maybe it's because MRF is only defined in the client. In the 1.3 version will be in both

**Comment by nicolaslopezj** [comment]
I created a npm version of this package

https://github.com/nicolaslopezj/simple-react-form
