### ISSUE TITLE
Import files server side

### ISSUE THREAD

**Issue by macrozone** [nicolaslopezj/meteor-react-form#5]
Hi Nicolas,
cool work!

The package should export the components also on the server to enable SSR (e.g. with FlowRouter SSR).

Maybe this might be solved when we switch to npm?

**Comment by nicolaslopezj** [comment]
Yes it should, I will change that soon

**Comment by nicolaslopezj** [comment]
I created a npm version of this package and I think this is solved.

https://github.com/nicolaslopezj/simple-react-form
