### ISSUE TITLE
Define mrf simple-schema options server side too 

### ISSUE THREAD

**Issue by Sabst** [nicolaslopezj/meteor-react-form#7]
Using the schema basic example from the README file, I currently get on the server-side:
`Error: Invalid definition for createdAt field.`

IMO, this new optional `mrf`option is added on client side only (init.jsx) but it is required on server side too.
This should rather be defined in a .js file loaded on both client and server sides.

**Comment by nicolaslopezj** [comment]
I created a npm version of this package.

https://github.com/nicolaslopezj/simple-react-form

In this new version, you must define the simple-schema options yourself
